### ISSUE TITLE
Forked

### ISSUE THREAD

**Issue by kentcdodds** [aaronfrost/es6-workshop#1]
Hey @aaronfrost,

Thanks for this awesome repo guys. I'm presenting on es6 tomorrow night at a meetup and I'm going to use this for sure. I'm also doing a day long workshop in August at a conference and this will go really nicely. Planning on just running through it quickly with the meetup and having attendees go through it at the workshop.

Also as an FYI, I've changed my fork to use mocha and chai. Just my style. Also I'm planning on adding tests for a few other concepts.

I just wanted to let you know that your work is appreciated! Will definitely credit you at both events. Hope your workshop went well!

**Comment by aaronfrost** [comment]
Thanks @kentcdodds. Please, if u get a video of u using this content, please let us see it. Would love to hear the shout out.
